name: built_to_dockerhub 
on:  
  pull_request:
    paths-ignore:
      - 'k8s/**'
      - 'argocd/**'
    types:
      - closed
  workflow_dispatch:
    
permissions:
  contents: write
      
jobs:
  if_merged:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow-dispatch'
    name: Build and Push Docker Image   
    runs-on: ubuntu-latest 

    steps:
      - name: checkout source code
        uses: actions/checkout@v5
        with: 
          fetch-depth: 0

      - name: Set up Docker Buildx for multi-platform builds and efficiency
        uses: docker/setup-buildx-action@v3
      
      - name: Caching docker layers
        uses: actions/cache@v4 
        with: 
          path: /tmp/.buildx-cache 
          key: ${{ runner.os }}-buildx-${{ github.sha }} 
          restore-keys: ${{ runner.os }}-buildx-setup

      - name: cached npm dependencies 
        uses: actions/cache@v4
        with: 
          path: ~/.npm 
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Login to Docker Hub
        uses: docker/login-action@v3 
        with: 
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image 
        uses: docker/build-push-action@v6
        with: 
          context: .
          file: ./Dockerfile 
          push: true
          platforms: |
            linux/amd64
          tags: | 
            ${{ secrets.DOCKER_USERNAME }}/threadwise:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/threadwise:latest 
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Setup Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: built_image
          client-payload: |
            {
              "image_sha": "${{ github.sha }}"
            }   
